import MENU_ITEMS from "./menu-items";

const ACTIVE_MENUS = {
  INIT: [MENU_ITEMS.LOAD],
  LOAD: [MENU_ITEMS.SAVE, MENU_ITEMS.DATA, MENU_ITEMS.EDIT],
  SAVE: [MENU_ITEMS.LOAD, MENU_ITEMS.DATA, MENU_ITEMS.EDIT],
  DATA: [MENU_ITEMS.LOAD, MENU_ITEMS.SAVE, MENU_ITEMS.EDIT],
};

export default ACTIVE_MENUS;
