import MENU_ITEMS from "./menu-items";

const ACTIVE_MENUS = {
  INIT: [MENU_ITEMS.LOAD],
  LOADED: [MENU_ITEMS.LOAD, MENU_ITEMS.DATA, MENU_ITEMS.EDIT],
  LOAD: [MENU_ITEMS.DATA],
  SAVE: [MENU_ITEMS.LOAD, MENU_ITEMS.DATA],
  DATA: [MENU_ITEMS.LOAD, MENU_ITEMS.DATA, MENU_ITEMS.EDIT],
  EDIT: [MENU_ITEMS.LOAD, MENU_ITEMS.DATA, MENU_ITEMS.EDIT, MENU_ITEMS.ADD],
};

export default ACTIVE_MENUS;
